query allUsers($first: Int) {
    allUsers(first: $first) {
        id
        name
        createdAt
        email
        comments {
            id
            text
        }
        posts {
            id
            title
        }
    }
}
